name: build website

on:
  push:
    branches: ["release"]
  pull_request:
    branches: ["release"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Copy Codes
        uses: actions/checkout@v4

      - name: setup node@20.15.1
        uses: actions/setup-node@v4
        with:
          node-version: "20.15.1"

      - name: Install pnpm@9.13.2
        uses: pnpm/action-setup@v4
        with:
          version: 9.13.2

      - name: Install Dependencies.
        run: pnpm install

      - name: Build Dist.
        run: pnpm docs:build

      - name: Deploy To GitHub Page.🚀
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-page
          build_dir: docs/.vitepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
